HoplonMessages DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS Person;

Person ::= [19] SEQUENCE {
        name UTF8String,
        location INTEGER {home(0),field(1),roving(2)},
        age INTEGER OPTIONAL }
END